apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "urlshortener"
  BASE_URL: "http://127.0.0.1" # Update this to your local IP
