apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  selector:
    app: url-shortener
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer # Exposes the service externally using cloud provider's load balancer
